### ISSUE TITLE
Fix issues on MapStory Prod

### ISSUE THREAD

**Issue by jpierson-boundlessgeo** [MapStory/mapstory#1523] opened 2018-08-13 20:47 UTC

**Comment by cuttlefish** [comment] 2018-08-22 03:54
The prod only and staging/prod only auth problems seem to bow all be resolved.
A myriad of problems were fixed in the last few days. Most of them seem to be simply due to not updating in 10 or 11 months. There are some outstanding prod-only API bugs that have outstanding tickets from about a year ago. These seem to be caused by broken stories and layers, but we're not certain yet.
Stories are totally broken.
Some layers are working, others are totally broken. The confusion between `title`, `name`, and `typename` seems to continue to be a problem (it was about a year ago and was never resolved). I've resolved some related issues, but not the main one.

**Closed as completed** 2018-08-24 18:16 UTC
