### ISSUE TITLE
New mapstories have no initial thumbnail created

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#313] opened 2016-12-19 06:46 UTC
We are not generating any original thumbnails for new stories anymore. All appear as an empty image.

A first effort model could be to grab the image at the last slice of Chapter 1. This will guarantee that there is some data features to visualize. And, every story will have 1 chapter.

Users can already also upload their own thumbnail to override the auto-thumbnail. But we need to at least provide one to start.

In the future, it would be cool to have an auto animated-GIF generator that takes a number of slices from the story.

(This is a restatement of MSSS-280 https://issues.boundlessgeo.com:8443/browse/MSSS-280)

**Comment by jonpmarino** [comment] 2017-07-19 02:56
Re-opening. It appears on beta that no default thumbnail is being generated on newly published stories.

![screen shot 2017-07-18 at 9 43 47 pm](https://user-images.githubusercontent.com/2573761/28348626-a9a16286-6c03-11e7-91c5-79fcc8946820.jpg)

**Comment by Coop56** [comment] 2017-12-01 18:42
Maps now generate thumbnails, but this will require a front end change to Explore.  I spoke with @emilyashley about what needs to happen and she's going to knock that out.

**Comment by Coop56** [comment] 2018-04-16 18:49
Duplicate of #1304, closing.

**Closed as completed by Coop56** 2018-04-16 18:49 UTC
Labels: bug, feature
