### ISSUE TITLE
Frame tab didn’t open a new tab

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1711] opened 2018-10-05 13:17 UTC
Frame tab didn’t open a new tab, added the form at the bottom of whichever tab is currently open (throwing a lot of digest errors in the log) (pri 1) - add a layer, then add a frame, seems to only apply to

**Comment by Coop56** [comment] 2018-11-05 16:56
Duplicate of #1588.  Closing.

**Closed as completed by Coop56** 2018-11-05 16:56 UTC
