### ISSUE TITLE
GeoNode Layers Endpoint not working

### ISSUE THREAD

**Issue by DanielJDufour** [MapStory/mapstory#1245] opened 2018-02-17 03:02 UTC
Navigate to https://mapstory.org/api/layers and see:
![screenshot 2018-02-16 at 9 56 21 pm](https://user-images.githubusercontent.com/4313463/36337431-45ab6e9e-1364-11e8-8b6f-86ca718c5200.png)

Here's an example of what it should like:
![screenshot 2018-02-16 at 9 58 58 pm](https://user-images.githubusercontent.com/4313463/36337446-a244f242-1364-11e8-8121-f180ef446f2e.png)

Couldn't find another issue open on this, but if there is one feel free to close this one :-)

**Comment by cuttlefish** [comment] 2018-02-17 04:46
I thought this was a dupe of #1216 but it's a different endpoint.

Seems to be a similar problem though. The error doesn't occur locally or on staging so I suspect there's some bad data on prod that's causing a problem.

Thanks for the heads up!

**Comment by DanielJDufour** [comment] 2018-02-17 07:29
You're very welcome.  Thanks for the prompt reply!

**Closed as completed** 2018-08-24 18:23 UTC
Labels: bug
