### ISSUE TITLE
Docker dev for  Windows Host

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory#790] opened 2017-06-24 14:23 UTC
Reminder we need to find a way to make work for a dev environment based on ubuntu vm in a Windows host. Coop was also interested - but he went for dual boot option to avoid this. Not something developers should be forced to do.

**Comment by Coop56** [comment] 2017-06-24 16:33
Just to clarify - I don't need Windows functionality so I think it's just you @rob-metalinkage.  I wouldn't do web development on Windows even if it was an option.  My dual boot is for game development on Windows / web development on Linux.

**Comment by cuttlefish** [comment] 2017-06-26 18:37
Windows Home editions don't support hardware acceleration for virtualization. This prevents Docker's provided support from working. Windows Pro is not a problem. This lack of hardware VM support means that it'll be slow.
Vagrant's docker-compose support is currently broken and won't be fixed until the next version gets released.
I'll just make a simple VM identical to the hosts we use in production and get the shared dirs working.

**Comment by cuttlefish** [comment] 2017-06-28 08:33
A Vagrantfile has been added to the `deployments` branch of `cuttlefish/mapstory`.
`vagrant up` from the docker directory should work.
You'll need to add "192.168.123.45 docker" to your hosts file.
I don't have a copy of Home edition installed to test this against.

**Comment by rob-metalinkage** [comment] 2017-06-28 10:55
Thank tyler... i'll get on this as soon as get back in the office next
week.

Rob

**Comment by rob-metalinkage** [comment] 2017-07-03 04:31
Kicking this off - will note questions/thoughts here as I go
1) all the READMEs are kind of irrelevant perhaps and need updating - happy to help with this process - we should have a discussion as to what goes where - what is top README etc.
2) is there anything magic about the 192.168.123.45 IP address - is this configured somewhere we have to match it?
3) vm target is debian/contrib-jessie64 - is this important enough we should document what version will be installed - what are the actual dependencies - what if a different vm was already in use, which will certainly be the case for some future update cycle
4) what are the system requirements and where should these be documented
5) what are the potential conflicts - if you have a vm already for some other purpose - what could go wrong (e.g.  allocated ip or port clash?)
6) after running vagrant up  how to connect (http and ssh)

Docker script ran with no reported errors
afterwards: vagrant ssh works
http://192.168.123.45 doesnt
vagrant@contrib-jessie:~$ sudo supervisorctl
sudo: supervisorctl: command not found

so where to from here?

**Comment by rob-metalinkage** [comment] 2017-07-06 20:00
docker build ( docker-compose build --pull; docker-compose up -d) failed with
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.2561439912
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall open

npm ERR! nospc ENOSPC: no space left on device, open 'npm-debug.log.2561439912'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/mapstory/mapstory/static/npm-debug.log
ERROR: Service 'django_volumes' failed to build: The command '/bin/sh -c set -ex     && npm install     && rm -rf ~/.npm     && rm -rf /tmp/npm-*     && bower install     && rm -rf ~/.cache/bower' returned a non-zero code: 228

**Comment by rob-metalinkage** [comment] 2017-07-18 11:44
robatkinson [12:21 PM] 
ok i see why the box choice:  on ubuntu/xenial needs sudo apt-get install docker, docker-compose  but then i had to update docker manually ... AFAICT having the vagrant provision docker should be safe regardless of the chosen box?


robatkinson [2:38 PM] 
claims to have finished - but there is nothing listening to the 80 port on the ip address.  found the host_provision.sh script - possibly thats workable but it also specifies debian-jessie.  Guess I need to revert again for some clues on which part to try to fix...

**Comment by rob-metalinkage** [comment] 2017-07-26 21:26
See #875 for overall requirements. Main issue for Windows specifically is choosing the right vagrant box, setting disk size if necessary and then setting up networking so can access install from Windows host.

**Comment by Coop56** [comment] 2017-07-26 22:09
Windows as a host machine already works.  Docker runs on Windows already.  I just confirmed on my own Windows machine.  I downloaded Docker from here - https://store.docker.com/editions/community/docker-ce-desktop-windows and then followed the instructions on our main README and the Docker prompts.  No additional UNIX based VM required.

**Comment by rob-metalinkage** [comment] 2017-07-26 23:43
So you are saying the mapstory install runs on Windows as a host OS?  AFAICT the docker container uses the host OS and  
"Requires Microsoft Windows 10 Professional or Enterprise 64-bit. For previous versions get Docker Toolbox." 

so for vanilla Windows (for the majority of people who have Windows based systems as standard work environments, a vm will still be required I think. 

We need to update the requirements in the README if in fact we are confident it works with the specific case of WindowsPro/Docker

**Comment by Coop56** [comment] 2017-07-27 03:55
In the cases of older Windows versions they can use Docker Toolbox.  https://docs.docker.com/toolbox/overview/  Most web developers are going to be using a UNIX based OS.  If they're trying to do web development on Windows they likely already know how to work around it's shortcomings.  I have Windows 10 Pro on every computer I own, so I can't test if our current setup works on Windows Home, but it should by using Docker Toolbox.

**Comment by rob-metalinkage** [comment] 2017-07-27 08:30
Cant really close as issue until its been tested and documentation complete and up to date.  

Having researched its obvious that its worth supporting winds Pro and docker tools (which should work on both Windows Home and current MacOs). These are all perfectly reasonable OS's to support - all the different flavours of *nix can probably be assumed to have greater knowledge and be able to adapt from single Unix build.

**Comment by rob-metalinkage** [comment] 2017-07-27 08:38
Build using docker_tools ran without error.  Site not found however using either http://docker/ or the IP http://192.168.99.100/

curl from within docker shell also fails
$ curl -i  http://docker/
curl: (7) Failed connect to docker:80; No errors 

$ docker-compose ps

             Name                            Command               State                                Ports
-----------------------------------------------------------------------------------------------------------------------------------------
mapstorydocker_celery_1           /opt/run.sh --celery             Exit 1
mapstorydocker_django_1           /opt/run.sh --collect-stat ...   Exit 2
mapstorydocker_django_volumes_1   /bin/sh -c chown -R mapsto ...   Exit 0
mapstorydocker_elasticsearch_1    /docker-entrypoint.sh elas ...   Up       0.0.0.0:9200->9200/tcp, 9300/tcp
mapstorydocker_geoserver_1        /opt/run.sh                      Up       8080/tcp
mapstorydocker_nginx_1            /bin/sh -c /opt/run.sh           Exit 1
mapstorydocker_pgadmin_1          /run.sh --init-db --serve        Up       5050/tcp
mapstorydocker_postgres_1         docker-entrypoint.sh postgres    Up       5432/tcp
mapstorydocker_protractor_1       /bin/true                        Exit 0
mapstorydocker_rabbitmq_1         run.sh rabbitmq-server           Up       15671/tcp, 15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
mapstorydocker_selenium_1         /opt/bin/entry_point.sh          Up       4444/tcp

**Comment by rob-metalinkage** [comment] 2017-07-27 08:41
PS - once i've tested this i'll upgrade to Windows Pro for performance, but still worthwhile having a shot at getting this running IMHO.   if docker_tools doesnt work then original vagrant/virtualbox is OK - provided that the network config and system requirements are handled properly.

**Comment by Coop56** [comment] 2017-07-27 14:04
Did you add to your hosts file?  Check the README for what needs added there.  Also it looks like the Django container failed.  Do you have the logs from that?

**Comment by Coop56** [comment] 2017-07-27 19:31
We spoke about this on the developer sync today.  We made the decision not to spend additional time on making sure Windows Home editions are supported by our build. Our recommendation is to use Linux or OSX, Windows 10 Pro works as well using the same instructions.  We won't be supporting Windows Home.

**Comment by rob-metalinkage** [comment] 2017-07-29 05:34
$ docker-compose logs django
Attaching to mapstorydocker_django_1
django_1          | Testing permissions...
django_1          | Permissions look good
django_1          | Collecting static files for dev deployment
django_1          | /opt/run.sh: 70: cd: can't cd to mapstory/static

I'll give this one more go then switch to PRO...

**Comment by rob-metalinkage** [comment] 2017-07-31 08:54
updated to PRO

django container fails:

PS C:\repos\github\mapstory> docker-compose logs django
Attaching to mapstory_django_1
django_1          | Testing permissions...
django_1          | touch: cannot touch ÔÇÿ/srv/mapstory/cover/.ignore_f50b93cda6f0ÔÇÖ: Permission denied

**Comment by sarasafavi** [comment] 2017-07-31 15:25
@davisc Clarence can you weigh in here? It sounds like the management decision made at dev sync last week hasn't been properly communicated outside of those who were on the hangout.

@rob-metalinkage please see @Coop56's posts elsewhere in this thread: if you're unable to get a working development environment on your machine using the instructions used by the rest of the dev team, suggest googling errors or using the #100-percent Slack channel to try & raise some help debugging your machine's issues. Too many dev cycles have been sunk into this issue already, and as it appears to only affect one developer's individual environment I'm closing this issue before we get even further down the rabbithole.

**Closed as completed by sarasafavi** 2017-07-31 15:25 UTC
Labels: blocker

**Comment by rob-metalinkage** [comment] 2017-08-04 05:13
have working environment now - a number of fixes to .gitattributes and documentation required to complete this task. Should be reopened and closed when PRs accepted for these fixes.
