### ISSUE TITLE
User can no longer re-arrange chapter order in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#859] opened 2017-07-24 16:59 UTC
**Sender**: jonpmarino@gmail.com
**Comment**: We used to be able to re-arrange chapter order. Looks like that is gone?
[Open #186 in Usersnap Dashboard](https://usersnap.com/a/#/mapstory-beta/p/mapstory-beta-abc33389/186)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-12/06-27/72eb2c4e-bd65-4522-89a5-33ed5bd5e92c.png'>![Usersnap Feedback - We used to be able to re-arrange chapter order. Looks like that is gone?](https://usersnappublic.s3.amazonaws.com/2017-05-12/06-27/c702e2cb-2854-41da-a08e-80d499fde833.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-12/06-27/72eb2c4e-bd65-4522-89a5-33ed5bd5e92c.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://mapstory.org/story/new?tour](https://mapstory.org/story/new?tour)
**Screen size**: 1440 x 900 **Browser size**: 1431 x 737

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by Coop56** [comment] 2017-09-25 16:39
Rearranging chapters is still working as intended, just tested on beta.  Closing.

**Closed as completed by Coop56** 2017-09-25 16:39 UTC
