### ISSUE TITLE
Layer Editor is accessible to unauthed users

### ISSUE THREAD

**Issue by cuttlefish** [MapStory/mapstory#508] opened 2017-03-02 15:40 UTC
When not logged in, I was able to access the Layer Editor.
When following links, it correctly asks you to log in. When going straight to the URL it does not.

![image](https://cloud.githubusercontent.com/assets/1152120/23514159/45da1a72-ff1b-11e6-8907-3b5b6a0c76fd.png)

**Comment by emilyashley** [comment] 2017-03-02 17:34
This [commit](https://github.com/MapStory/geonode/commit/35f66a3cba8a7aae88654818b33c76200a6440aa) can fix that, but it's editing our geonode fork. Is this something that geonode would want to prevent as well? or do they handle it a different way? 

note: I'm unsure if this covers logged-in users hard linking to a layer that hasn't been opened up for community editing

**Comment by sarasafavi** [comment] 2017-03-02 19:54
> This commit can fix that, but it's editing our geonode fork. Is this something that geonode would want to prevent as well? or do they handle it a different way?

So GeoNode doesn't specifically require auth for that view because any persistent changes (e.g., saving a new map from that page) require auth - see e.g., http://demo.geonode.org/maps/new

_Edit to make my original comment clearer:_

@cuttlefish TL;DR: essentially per upstream GeoNode this is "working as intended". 

Since the layer is publicly viewable already, it can also be viewed within the new map page (or in Mapstory's case, "edit layer" page) page without authenticating. However saving any changes still prompts for login (in vanilla GeoNode) or else throws a permission error (in MapStory).

If MapStory wants different behavior than core GeoNode, we can patch this view on the MapStory side of the house -- otherwise IMO issue can be closed.

**Comment by jonpmarino** [comment] 2017-03-24 19:13
test...(note to self) what happens if its private

**Comment by Coop56** [comment] 2017-09-25 15:54
Closing as this is no longer the case.

**Closed as completed by Coop56** 2017-09-25 15:54 UTC
Labels: bug
