### ISSUE TITLE
Legend in MapStory viewer is not representing styles

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#830] opened 2017-07-14 19:25 UTC
(Based on 2 tests with different layers. Original report in UserSnap 187. See rapidfeedbackteam channel in Slack. The example described below is based on https://beta.mapstory.org/story/63.

In composer, when a user creates a new style for a layer, the legend updates to represent the newly saved styling information.

![screen shot 2017-07-14 at 2 19 44 pm](https://user-images.githubusercontent.com/2573761/28227564-2fba8d8c-68a0-11e7-830b-5365bbe98ebc.jpg)

However, once a story is published, the legend seems to show original or default styling information, rather than the style that the storyteller created and saved.

![screen shot 2017-07-14 at 2 21 02 pm](https://user-images.githubusercontent.com/2573761/28227596-499a42a6-68a0-11e7-9b61-3c3fa3cf94ca.jpg)

 It looks like the new style _is_ persisted on the map canvas, however. So something is just not being updated in the viewer legend.

![screen shot 2017-07-14 at 2 21 20 pm](https://user-images.githubusercontent.com/2573761/28227604-50a414d2-68a0-11e7-8df9-21e5035a1cdb.jpg)

**Comment by cuttlefish** [comment] 2017-08-16 14:40
Is this issue still a problem?

**Comment by Coop56** [comment] 2017-08-27 21:13
Just confirmed that on beta this is still an issue.

**Comment by davisc** [comment] 2017-09-14 00:08
This code was added here https://github.com/MapStory/story-tools/commit/f3b35c26d52d29c9a82880a33dcef5ef426c87f9#diff-ed9c0ae77e913c0e15b7f0664f3cd2ed ... but chrome tools on beta.mapstory.org shows that line of code as being commented out.

<img width="750" alt="screen shot 2017-09-13 at 7 08 29 pm" src="https://user-images.githubusercontent.com/947403/30406375-f5ea8d86-98b6-11e7-99e6-a5801931716d.png">

**Comment by davisc** [comment] 2017-09-14 00:11
Looks like the distro was built from a different source that introduced the commented out line.

**Comment by davisc** [comment] 2017-09-14 00:15
Fixed in https://github.com/MapStory/story-tools/commit/33f80e29f868dadcd8352a4fd41f9a9de0a095fc .. @cuttlefish need to bump storytools to that rev.

**Comment by emilyashley** [comment] 2017-09-18 19:41
Cool, bumped here https://github.com/MapStory/mapstory/commit/cce50b976eb42499408678a0584b122d6a4dedf0

**Comment by emilyashley** [comment] 2017-09-20 20:25
I had to wiggle bower a bit to pull in the story-tools changes (cc: @cuttlefish), but confirmed this works locally.  closing now.

![screen shot 2017-09-20 at 3 23 03 pm](https://user-images.githubusercontent.com/15912063/30665744-ae29ccd0-9e17-11e7-8e33-7349859425d3.png)

**Comment by emilyashley** [comment] 2017-09-30 06:32
Reopened because changes to the legend weren't persisting with continued storytools development. They were committed to the dist file not the source files. See open PR above for fix.

<img width="958" alt="screen shot 2017-09-30 at 1 30 07 am" src="https://user-images.githubusercontent.com/15912063/31043301-10553a84-a57f-11e7-8448-1c262b37938a.png">

**Closed as completed** 2017-10-02 21:56 UTC
Labels: bug
