### ISSUE TITLE
If a user's first layer is from the create modal, their init commits are attributed to 'admin'

### ISSUE THREAD

**Issue by emilyashley** [MapStory/mapstory#504] opened 2017-03-02 06:53 UTC
<img width="1270" alt="screen shot 2017-03-01 at 5 03 12 pm" src="https://cloud.githubusercontent.com/assets/15912063/23497415/862524ba-fee8-11e6-93b7-4af7ca1a185c.png">
<img width="354" alt="screen shot 2017-03-01 at 5 31 43 pm" src="https://cloud.githubusercontent.com/assets/15912063/23497420/8c01c7ee-fee8-11e6-872d-422a184b1eef.png">

**Comment by emilyashley** [comment] 2017-03-02 06:55
reminder to self: verify this fully works https://github.com/MapStory/mapstory/commit/b057684510035c1ff8ae5a5ec4c2f806b45c1bfe

**Comment by Coop56** [comment] 2017-03-16 19:24
@emilyashley This looks like it should work, if you want to PR it I will review it to be sure and merge it in.

**Comment by jonpmarino** [comment] 2017-03-21 21:43
just confirmed again on demo with https://demo.mapstory.org/layers/geonode:nba_basketball_teams. StoryLayer created by michaeljordan before that account had done an import.

**Comment by Coop56** [comment] 2017-03-24 22:08
Resolved by #565.

**Closed as completed** 2017-04-18 16:02 UTC
Labels: bug
