### ISSUE TITLE
Create StoryFrames by pulling from top-left to bottom right

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory#1650] opened 2018-10-03 20:33 UTC
As a user I expect the StoryFrame drawing workflow to work like a cropping tool or rubber band...pulling the box from top-left to bottom right.

Right now it pulls from bottom right to top left.

**Comment by shawnkendrick** [comment] 2018-10-24 15:06
Duplicate of issue: #1744, Refactor how Bounding Box can be drawn

**Closed as completed by shawnkendrick** 2018-10-24 15:06 UTC
